/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.ImageIcon;

public class Caffein_bst extends javax.swing.JFrame {

    ImageIcon imagecofee = new ImageIcon("pure cofee.jpg");
    ImageIcon imagetea = new ImageIcon("Tea cofee.jpg");
    ImageIcon imagecap = new ImageIcon("cappuccino.jpg");
    ImageIcon imageesp = new ImageIcon("espesso.jpg");
    
    ImageIcon imagechi = new ImageIcon("brioche.jpg");
    ImageIcon imagecro = new ImageIcon("croissant.jpg");
    ImageIcon imagetoa = new ImageIcon("toast.jpg");
    ImageIcon imagepas = new ImageIcon("pastry.jpg");
    
    public Caffein_bst() {
        initComponents();
        this.setLocationRelativeTo(null);
        pic.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ent = new javax.swing.JButton();
        cle = new javax.swing.JButton();
        exi = new javax.swing.JButton();
        sub = new javax.swing.JLabel();
        tax = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        txtsub = new javax.swing.JTextField();
        txttax = new javax.swing.JTextField();
        txttot = new javax.swing.JTextField();
        cof = new javax.swing.JRadioButton();
        tea = new javax.swing.JRadioButton();
        esp = new javax.swing.JRadioButton();
        cap = new javax.swing.JRadioButton();
        cro = new javax.swing.JCheckBox();
        toa = new javax.swing.JCheckBox();
        pas = new javax.swing.JCheckBox();
        chi = new javax.swing.JCheckBox();
        pic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(161, 135, 91));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusTraversalPolicyProvider(true);
        setForeground(java.awt.Color.gray);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(101, 70, 49));
        jLabel1.setText("C a f f e i n   b o o s t e r ");

        ent.setText("Enter");
        ent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entActionPerformed(evt);
            }
        });

        cle.setText("Clear");
        cle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleActionPerformed(evt);
            }
        });

        exi.setText("Exit");
        exi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiActionPerformed(evt);
            }
        });

        sub.setText("SubTotal");

        tax.setText("Tax");

        tot.setText("Total");

        cof.setText("Cofee             Rs. 225.00");
        cof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cofActionPerformed(evt);
            }
        });

        tea.setText("Tea                  Rs.175.00");
        tea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teaActionPerformed(evt);
            }
        });

        esp.setText("Espresso         Rs.375.00");
        esp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espActionPerformed(evt);
            }
        });

        cap.setText("cappuccino   Rs.350.00");
        cap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capActionPerformed(evt);
            }
        });

        cro.setText("Croissant Bread    Rs.180.00");
        cro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                croActionPerformed(evt);
            }
        });

        toa.setText("Toast Bread           Rs.200.00");
        toa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toaActionPerformed(evt);
            }
        });

        pas.setText("Pastry                     Rs.220.00");
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });

        chi.setText("Chicken Bun         Rs.175.00");
        chi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiActionPerformed(evt);
            }
        });

        pic.setText("pic");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(exi)
                                    .addComponent(ent)
                                    .addComponent(cle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tot, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tax, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sub)
                                    .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsub)
                            .addComponent(txttax)
                            .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(esp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cof, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(tea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(toa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pas, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(chi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toa)
                        .addGap(5, 5, 5)
                        .addComponent(pas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub)
                            .addComponent(txtsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(cof)
                        .addGap(18, 18, 18)
                        .addComponent(tea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cap)
                        .addGap(18, 18, 18)
                        .addComponent(esp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tax)
                            .addComponent(txttax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tot)
                            .addComponent(txttot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exi)))
                .addGap(26, 26, 26)
                .addComponent(pic, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel1.getAccessibleContext().setAccessibleName("Caffein Booster");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teaActionPerformed
        //select tea option
        if(tea.isSelected())
            cof.setSelected(false);
            esp.setSelected(false);
            cap.setSelected(false);
        pic.setIcon(imagetea);    
        
    }//GEN-LAST:event_teaActionPerformed

    private void espActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espActionPerformed
        //select capettino option
        if(esp.isSelected())
            cof.setSelected(false);
            tea.setSelected(false);
            cap.setSelected(false);
        pic.setIcon(imageesp);    
    }//GEN-LAST:event_espActionPerformed

    private void capActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capActionPerformed
        //select espesso option
        if(cap.isSelected())
            cof.setSelected(false);
            tea.setSelected(false);
            esp.setSelected(false);
        pic.setIcon(imagecap);
    }//GEN-LAST:event_capActionPerformed

    private void entActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entActionPerformed
        double total;
        double subtotal = 0;
        double taxRate = 25.00;
        double tax;
        
        if(cof.isSelected()){
            subtotal = subtotal + 225.00 ;
            
        }else if(tea.isSelected()){
            subtotal = subtotal + 175.00;
        }else if(cap.isSelected()){
            subtotal = subtotal + 350.00;
        }else if(esp.isSelected()){
            subtotal = subtotal + 375.00;
        }
        if(chi.isSelected()){
            subtotal = subtotal + 175.00;
        }if(cro.isSelected()){
            subtotal = subtotal + 180.00;
        }if(toa.isSelected()){
            subtotal = subtotal + 200.00;
        }if(pas.isSelected()){
            subtotal = subtotal + 220.00;
        }
        txtsub.setText(Double.toString(subtotal));
        
        subtotal = Double.parseDouble(txtsub.getText());
        tax = subtotal + taxRate;
        total = tax + subtotal;
        
        txttax.setText(Double.toString(tax));
        txttot.setText(Double.toString(total));
    }//GEN-LAST:event_entActionPerformed

    private void exiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiActionPerformed
        //exit our frame
        System.exit(0);
    }//GEN-LAST:event_exiActionPerformed

    private void cleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleActionPerformed
        //clear 
        cof.setSelected(false);
        tea.setSelected(false);
        cap.setSelected(false);
        esp.setSelected(false);
        chi.setSelected(false);
        toa.setSelected(false);
        pas.setSelected(false);
        cro.setSelected(false);
        txtsub.setText("");
        txttax.setText("");
        txttot.setText("");
    }//GEN-LAST:event_cleActionPerformed

    private void cofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cofActionPerformed
       //select tea option
        if(cof.isSelected())
            tea.setSelected(false);
            esp.setSelected(false);
            cap.setSelected(false);
        pic.setIcon(imagecofee);
    }//GEN-LAST:event_cofActionPerformed

    private void chiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiActionPerformed
        pic.setIcon(imagechi);
    }//GEN-LAST:event_chiActionPerformed

    private void croActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_croActionPerformed
        pic.setIcon(imagecro);
    }//GEN-LAST:event_croActionPerformed

    private void toaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toaActionPerformed
        pic.setIcon(imagetoa);
    }//GEN-LAST:event_toaActionPerformed

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
       pic.setIcon(imagepas);
    }//GEN-LAST:event_pasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caffein_bst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caffein_bst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caffein_bst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caffein_bst.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caffein_bst().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton cap;
    private javax.swing.JCheckBox chi;
    private javax.swing.JButton cle;
    private javax.swing.JRadioButton cof;
    private javax.swing.JCheckBox cro;
    private javax.swing.JButton ent;
    private javax.swing.JRadioButton esp;
    private javax.swing.JButton exi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox pas;
    private javax.swing.JLabel pic;
    private javax.swing.JLabel sub;
    private javax.swing.JLabel tax;
    private javax.swing.JRadioButton tea;
    private javax.swing.JCheckBox toa;
    private javax.swing.JLabel tot;
    private javax.swing.JTextField txtsub;
    private javax.swing.JTextField txttax;
    private javax.swing.JTextField txttot;
    // End of variables declaration//GEN-END:variables
}
